#!/bin/bash
#
# $PROJECT specific profile
# All variable are overrulable in your own ~/etc/crawl-profile

set -e

: ${AWS_CP:=aws --no-sign-request s3 cp}
: ${S3_BUCKET:=s3://commoncrawl}
: ${LOCKS:=$FASTDISK/$PROJECT/locks}
: ${LOGS:=$FASTDISK/$PROJECT/logs}
export AWS_CP S3_BUCKET LOCKS LOGS

: ${CRAWL_PATHS_TODO:=$BIGDISK/$PROJECT/CRAWL-paths-todo}
: ${CRAWL_WARC_CACHE:=$FASTDISK/$PROJECT/CRAWL-warcs-incoming}
: ${CRAWL_WARC_CACHE_SIZE:=10}
export CRAWL_PATHS_TODO CRAWL_WARC_CACHE CRAWL_WARC_CACHE_SIZE

: ${WAT_PATHS_TODO:=$BIGDISK/$PROJECT/WAT-paths-todo}
: ${WAT_WARC_CACHE:=$FASTDISK/$PROJECT/WAT-warcs-incoming}
: ${WAT_WARC_CACHE_SIZE:=10}
export WAT_PATHS_TODO WAT_WARC_CACHE WAT_WARC_CACHE_SIZE

: ${WET_PATHS_TODO:=$BIGDISK/$PROJECT/WET-paths-todo}
: ${WET_WARC_CACHE:=$FASTDISK/$PROJECT/WET-warcs-incoming}
: ${WET_WARC_CACHE_SIZE:=10}
export WET_PATHS_TODO WET_WARC_CACHE WET_WARC_CACHE_SIZE

: ${PROCESS_DIRS:=$FASTDISK/$PROJECT/processing}
: ${MAX_CC_PARALLEL:=4}
export PROCESS_DIRS MAX_CC_PARALLEL

PERL5LIB+=":$PIPELINE_REPO/CommonCrawl/perl5/OSF-CommonCrawl/lib"

case "$COMMAND" in
process-batch | warc-pipeline)
    source "$PIPELINE_REPO/Pipeline/profile";;
esac
