#!/bin/bash

set -e

ETC="$HOME/etc"
[ -d "$ETC" ] || mkdir $ETC

BIN="$HOME/bin"
[ -d "$BIN" ] || mkdir $BIN

SCRIPT="$PWD/$0"
REPO="${SCRIPT%/*/*}"

#
### Install the configurable profile
#

PROFILE="$ETC/crawl-profile"

if [ ! -f "$PROFILE" ]
then TEMPLATE="$REPO/install/crawl-profile.template"

     perl -wpe <"$TEMPLATE" >"$PROFILE" "
       s!\\[% SCRIPT %\\]!$0!;
       s!\\[% DATE %\\]!$(date)!;
       s!\\[% REPO %\\]!$REPO!;
     "

     cat <<__CONFIGURE
*
*** now configure $PROFILE
*** then rerun 'make'
*
__CONFIGURE

fi

source "$PROFILE"

#
### The "run" wrapper to be used for cron
#

[ -f $BIN/run ] && chmod u+w $BIN/run
cp $REPO/install/run $BIN/run
chmod u=rx $BIN/run

#
### Some configuration checks
#

if [ -z "$BIGDISK" ]
then echo "You need to set BIGDISK to your bulk store." >&2
     exit 6    # ENXIO
fi

if [ ! -d "$BIGDISK" ]
then echo "BIGDISK '$BIGDISK' does not exist or not a directory." >&2
     exit 2    # ENOENT
fi

if [ -z "$FASTDISK" ]
then echo "You need to set FASTDISK to your bulk store." >&2
     exit 6    # ENXIO
fi

if [ ! -d "$FASTDISK" ]
then echo "FASTDISK '$FASTDISK' does not exist or not a directory." >&2
     exit 2    # ENOENT
fi


#
### Update all plugins
#


